# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{balbo}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wayne Larsen", "Chris Wanstrath"]
  s.date = %q{2009-11-02}
  s.description = %q{Balbo is a framework-agnostic way to render almost logic-free views.}
  s.email = %q{wayne@larsen.st}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     ".kick",
     "CONTRIBUTORS",
     "HISTORY.md",
     "LICENSE",
     "README.md",
     "Rakefile",
     "benchmarks/complex.erb",
     "benchmarks/complex.haml",
     "benchmarks/helper.rb",
     "benchmarks/mustache_complex.mustache",
     "benchmarks/mustache_complex.rb",
     "benchmarks/simple.erb",
     "benchmarks/speed.rb",
     "contrib/mustache.vim",
     "contrib/tpl-mode.el",
     "examples/app/app.rb",
     "examples/app/config.ru",
     "examples/app/default.balbo",
     "examples/app/index.balbo",
     "examples/app/profile.balbo",
     "examples/app/public/css/screen.css",
     "examples/app/public/css/styles.css",
     "examples/app/public/images/Italo_Balbo.jpg",
     "examples/comments.balbo",
     "examples/comments.rb",
     "examples/complex_view.balbo",
     "examples/complex_view.rb",
     "examples/double_section.balbo",
     "examples/double_section.rb",
     "examples/escaped.balbo",
     "examples/escaped.rb",
     "examples/inheritance.balbo",
     "examples/inheritance.rb",
     "examples/inner_partial.balbo",
     "examples/inner_partial.txt",
     "examples/namespaced.balbo",
     "examples/namespaced.rb",
     "examples/passenger.conf",
     "examples/passenger.rb",
     "examples/root.balbo",
     "examples/simple.balbo",
     "examples/simple.rb",
     "examples/template_partial.balbo",
     "examples/template_partial.rb",
     "examples/template_partial.txt",
     "examples/unescaped.balbo",
     "examples/unescaped.rb",
     "examples/view_partial.balbo",
     "examples/view_partial.rb",
     "lib/balbo.rb",
     "lib/balbo/blocks.rb",
     "lib/balbo/context.rb",
     "lib/balbo/sinatra.rb",
     "lib/balbo/template.rb",
     "lib/balbo/version.rb",
     "lib/rack/bug/panels/mustache_panel.rb",
     "lib/rack/bug/panels/mustache_panel/mustache_extension.rb",
     "lib/rack/bug/panels/mustache_panel/view.mustache",
     "spec/balbo_spec.rb",
     "spec/blocks_spec.rb",
     "spec/context_spec.rb",
     "spec/layout.balbo",
     "spec/spec_helper.rb",
     "spec/template_spec.rb",
     "spec/test.balbo"
  ]
  s.homepage = %q{http://github.com/wvl/balbo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Balbo is a framework-agnostic way to render almost logic-free views.}
  s.test_files = [
    "spec/balbo_spec.rb",
     "spec/blocks_spec.rb",
     "spec/context_spec.rb",
     "spec/spec_helper.rb",
     "spec/template_spec.rb",
     "examples/app/app.rb",
     "examples/comments.rb",
     "examples/complex_view.rb",
     "examples/double_section.rb",
     "examples/escaped.rb",
     "examples/inheritance.rb",
     "examples/namespaced.rb",
     "examples/passenger.rb",
     "examples/simple.rb",
     "examples/template_partial.rb",
     "examples/unescaped.rb",
     "examples/view_partial.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

